apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []

patches:
- target:
    kind: ConfigMap
    name: istio
    namespace: istio-system
  patch: |-
    - op: replace
      path: /data/mesh
      value: |
        accessLogFile: /dev/stdout
        defaultConfig:
          discoveryAddress: istiod.istio-system.svc:15012
          proxyMeta: {}
          tracing: {}
        defaultProviders:
          metrics:
          - prometheus
        enablePrometheusMerge: true
        rootNamespace: istio-system
        tcpKeepalive:
          interval: 5s
          probes: 3
          time: 10s
        trustDomain: cluster.local
        extensionProviders:
        - name: oauth2-proxy
          envoyExtAuthzHttp:
            service: oauth2-proxy.oauth2-proxy.svc.cluster.local
            port: 80
            headersToDownstreamOnDeny:
            - content-type
            - set-cookie
            headersToUpstreamOnAllow:
            - authorization
            - path
            - x-auth-request-email
            - x-auth-request-groups
            - x-auth-request-user
            includeRequestHeadersInCheck:
            - authorization
            - cookie
        meshNetworks: "networks: {}"
