apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-patcher
  namespace: istio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istio-patcher
  namespace: istio-system
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "patch", "update", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-patcher
  namespace: istio-system
subjects:
- kind: ServiceAccount
  name: istio-patcher
  namespace: istio-system
roleRef:
  kind: Role
  name: istio-patcher
  apiGroup: rbac.authorization.k8s.io
